version: "3.9"

services:
  eventmanagementsystem:
    container_name: event-management-system
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
