# Generated by Django 6.0.4 on 2026-04-20 12:07
from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        if User.objects.exists():
            return
        
        superuser = User.objects.create_superuser(
            username='admin',
            email="admin@admin.com",
            password='admin@admin.com"',
            last_login=timezone.now(),
        )
        superuser.save()

    operations = [
        migrations.RunPython(create_superuser),
    ]
