# Generated by Django 6.0.4 on 2026-04-19 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Speaker full name', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Speaker contact email', max_length=254, null=True)),
                ('bio', models.TextField(blank=True, help_text='Speaker biography', null=True)),
                ('title', models.CharField(help_text='Professional title (e.g., Senior Engineer at Google)', max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Social media links: {photo, linkedin, twitter, website, github, etc}', null=True)),
                ('expertise', models.JSONField(blank=True, default=list, help_text="Array of expertise areas: ['Python', 'AI', 'Cloud']", null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional speaker information', null=True)),
                ('creator', models.CharField(blank=True, db_index=True, help_text='User who created this speaker profile', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'db_table': 'speakers',
                'ordering': ['-created_at'],
            },
        ),
    ]
