# Generated by Django 6.0.4 on 2026-04-20 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='User who created this speaker', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speakers', to=settings.AUTH_USER_MODEL),
        ),
    ]
